apiVersion: v1
kind: Pod
metadata:
  name: network-tools-1
  labels:
    app: network-tools
spec:
  containers:
  - image: mboscovich/network-tools:latest
    imagePullPolicy: IfNotPresent
    name: network-tool
  restartPolicy: Always